/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.uv.tcswpractica02;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josealanth
 */
public class ListaEmpleadosGUI extends javax.swing.JInternalFrame {

    private JDesktopPane desktoppane = null;
            
    public ListaEmpleadosGUI(JDesktopPane desktoppane) {
        initComponents();
        llenarTabla();
        this.desktoppane = desktoppane;
    }

    private void llenarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) JTEmpleados.getModel();
        modelo.setRowCount(0);
        DAOEmpleado dao = new DAOEmpleado();
        for (PojoEmpleado emp : dao.findAll()) {
            modelo.addRow(new Object[]{
                emp.getClave(),
                emp.getNombre(),
                emp.getDireccion(),
                emp.getTelefono()
            });
        }
    }
    
    private Long seleccionarFila(){
        int fila = JTEmpleados.getSelectedRow();
        
        if(fila > -1){
             Object claveObj = JTEmpleados.getValueAt(fila, 0);
             return Long.parseLong(claveObj.toString());
        }else{
            return null;
        }
    }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTEmpleados = new javax.swing.JTable();
        JBMostrar_Datos = new javax.swing.JButton();
        JBEliminar = new javax.swing.JButton();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(650, 450));
        setPreferredSize(new java.awt.Dimension(650, 450));

        JTEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre", "Dirrecion", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTEmpleados);

        JBMostrar_Datos.setText("Mostrar Datos");
        JBMostrar_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMostrar_DatosActionPerformed(evt);
            }
        });

        JBEliminar.setText("Eliminar");
        JBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(JBMostrar_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(JBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBMostrar_Datos)
                    .addComponent(JBEliminar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBMostrar_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMostrar_DatosActionPerformed
        Long clave = seleccionarFila();
        if(clave != null){
            EmpleadoDatosGUI gui = new EmpleadoDatosGUI(clave);
            desktoppane.add(gui);
            gui.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Selecciona una fila");
        }
    }//GEN-LAST:event_JBMostrar_DatosActionPerformed

    private void JBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarActionPerformed
        Long clave = seleccionarFila();
        if(clave != null){
            int respuesta = JOptionPane.showConfirmDialog(null,
                "Desea elimiar este Empleado?",
                "Confirmas Elimicacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if(respuesta == JOptionPane.YES_OPTION){
            DAOEmpleado dao = new DAOEmpleado();
            if(dao.eliminar(clave) != null){
                JOptionPane.showMessageDialog(this,"Se elimino correctamente");
                llenarTabla();
            }else{
                JOptionPane.showMessageDialog(this,"Error al Eliminar");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Cancelacion Exitosa");
        }
        }else{
            JOptionPane.showMessageDialog(null,"Selecciona una fila");
        }
    }//GEN-LAST:event_JBEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEliminar;
    private javax.swing.JButton JBMostrar_Datos;
    private javax.swing.JTable JTEmpleados;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
